# Generated by Django 5.2.6 on 2025-10-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайній термін'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процесі'), ('completed', 'Завершена')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
